### PR TITLE
Review flow

### LINKED ISSUE #146: Implement HTTP2
Probably one of the important things when using the service in the real world, we have to enable https:

https://github.com/jillix/engine/blob/c8899067e149a7f3c3949c8a9686ec7c3bb7a5d8/lib/engine.js#L4

### LINKED ISSUE #150: Client require without full path
Make client side `require` work like in Node.js, without the need of the version and file path.
Current implementation:

``` js
var module = require("moduleName@version/path/main.js");
```

Node.js `require`:

``` js
var module = require("moduleName");
// ..or
var module = require("moduleName/path/file");
```

The difficulty is to get the right version, which is defined in the `package.json` of the parent module.

### LINKED ISSUE #180: Don't fingerprint resources in debug mode
When debugging client code, I have to set breakpoints every time I change a file a new fingerprint is generated and DevTools loses all the breakpoint information. The breakpoints can also contain watch expressions.

It would be nice to be able to deactivate fingerprinting for debugging purposes.

### LINKED ISSUE #194: Make session store pluggable.

### LINKED ISSUE #218: Stream binary data over socket
https://developer.mozilla.org/en-US/docs/Web/API/WebSocket#send()
http://blog.mgechev.com/2015/02/06/parsing-binary-protocol-data-javascript-typedarrays-blobs/
https://github.com/binaryjs/binaryjs

### LINKED ISSUE #271: Allow normal npm modules to be loaded as client modules
The client dependencies should support loading normal npm modules. For example, it would be nice to be able to load [`typpy`](https://github.com/IonicaBizau/node-typpy) on the client side, like this:

``` js
var Typpy = require("typpy");
```

...and all these, without a `composition` configuration.

Maybe using Browserify's [`require`](https://github.com/substack/node-browserify#brequirefile-opts) could be a solution. :dizzy: 

Currently, this is a big limitation. On the server side, this is possible, on client it is not.

### LINKED ISSUE #278: Callback buffer for client side instance (factory)
If an instances is cached but not yet initialized, due to resources which are still loading (Markup, Scripts), and the same instance is requested again `engine.load(instance)`. The cached instance will call a module method, before `init` is called.

### LINKED ISSUE #280: Using ALTR to get DOM info
Currently it's a little bit hacky to get the attribute values of a DOM element reference:

``` js
/foo/{myDomElement.attributes.0.value}
```

Since the `attributes` are an array-like object, we cannot be sure we get the correct attribute.

What other related limitations we have here?

### LINKED ISSUE #282: If a module is not installed, but needed, an error should appear
It happened that an instance was emitting an event to another instance of a module that was not installed and no error appeared.

After debugging the things I saw the module is not installed. Instead of this, engine should notify the developer that the module is missing, like it does in the other cases (file not found, etc.).

### LINKED ISSUE #283: Uncaught TypeError: stream.write is not a function
Sometimes this error appears: `Uncaught TypeError: stream.write is not a function`

### LINKED ISSUE #284: "Error: Invalid composition <name>"–Why?
This error message should be improved: `Error: Invalid composition "<name>"`–currently the only relevant information is that the composition is invalid and nothing more.

### LINKED ISSUE #285: Flow method arguments merging
There are three types of options/config/args in engine:
1. Instance config
2. Flow method args `["method", "arg"]`
3. The data chunk

Often there is options data in the data chunk itself. It would be nice to have a config like the `:ALTR` to get the options out of a data chunk, so the method handler does not have to do this step manually.

Proposal:

``` json
[
    "myMethod", {"optionX": "{from.data.chunk}"}
]
```

Further there could be a way to define default configs for every method, maybe in form if JSdocs, in the instance config or hard coded in the code. For the the module has to take care of ensuring the default values.

### LINKED ISSUE #286: 2x flow emits don't work
Such a config is not working:

``` json
[
    [">flow", "eventA"],
    [">flow", "eventB"]
]
```

### LINKED ISSUE #287: Unreadable error
`Object {msg: "[object Object]", level: "error"}`

https://github.com/jillix/engine/blob/7ca85f73353b055aaf993350a5eda53d67aa8bbc/lib/client/engine.js#L40

### LINKED ISSUE #289: Invalid composition after invalid json
1. Change an instance file to contain JSON syntax errors.
2. Load the app in the browser.
3. You will see an error saying that the JSON is invalid.
4. Fix the JSON in the instance.
5. Load again the app in the browser.

**Expected:** Work properly
**Actual behavior**: An error is appearing saying the composition is invalid.

### LINKED ISSUE #290: Uncaught TypeError: Cannot read property 'indexOf' of null(…)
`scripts` is an array containing `null` references:

``` js
["engine-sidebar@1.1.0/client/index.@91de10d.js", "engine-sidebar@1.1.0/client/libs/sidebar.@01dfb90.js", "/libs/jquery.js", null, null, null, null, null, null, null, null, "/libs/jquery.js"]
```

https://github.com/jillix/engine/blob/ed9a00b8166253ccfbd271221bc27e31ab1c2c6e/lib/client/resource.js#L103

### LINKED ISSUE #291: How do we integrate data and stream handlers?
Currently there is a buggy behavior when saving the Builder editor value, in Service:
- https://github.com/jillix/service/blob/master/composition/app_builder_layout.json#L71-L75
- https://github.com/jillix/engine-editor/blob/master/client/index.js#L198-L205

### LINKED ISSUE #292: Server emit to an instance with no client files will cause app to freeze
A server emit similar to this `["server_custom/flow", "@testFunction"]` where `server_custom` is an instance with no client files, will break the app. Note: `["flow", "@server_custom/testFunction"]` will work.
screenshot 2015-10-23 19 24 14

### LINKED ISSUE #294: ALTR: Wrap the data in object
It would be amazing to have the possibility to wrap data into an object using `ALTR`. For example:

**input data**:

``` json
{ "foo": "bar" }
```

But let's suppose we really need this object wrapped into another object, so the output would be:

``` json
{
    "wrapper": { "foo": "bar" }
}
```

### LINKED ISSUE #295: Document the flow example
@adioo Can you please add inline comments for each element in [this list](https://github.com/jillix/engine/tree/flow-review#flow-config-all-combinations)?

That would make the understanding simpler.

### PR DESCRIPTION
**Pull request by ottiker**
Remove existing limitation and ensure flow works as expected.

Fixes #146 
Fixes #150 
Fixes #180
Fixes #194
Fixes #218
Fixes #271 
Fixes #278 
Fixes #280 
Fixes #282 
Fixes #283 
Fixes #284 
Fixes #285 
Fixes #286 
Fixes #287 
Fixes #289 
Fixes #290 
Fixes #291
Fixes #292 
Fixes #294
Fixes #295

### CODE REVIEW

File: lib/client/engine.js [hunk 1]
```diff
@@ -34,12 +34,12 @@ engine.load = function (name, role, callback, loaderInstance) {
     }
 
     // get composition
-    engine.flow('C', true).error(function (err, stream) {
+    engine.flow('C', true).error(function (stream, err) {
```
Comment (IonicaBizau) [inline lib/client/engine.js]: Will this affect all the modules _again_?
